version: "3"

services:
  app:
    container_name: agro
    build:
      context: .
      dockerfile: Dockerfile
    image: agro:latest
    ports:
      - 8888:8080

  mongo:
    container_name: mongodb-datastore
    image: mongo:latest
    ports:
    - 27019:27017
